controllers:
    resource: ../src/Controller/
    type: attribute

authentication_token:
    path: /authentication_token
    methods: ['POST']

api_login_check:
    path: /login
    methods: ['POST']
